### ISSUE TITLE
Stealed?

### ISSUE THREAD

**Issue by Rishisuperyo-Op** [Itzdipesh/itzdipesh#1]
Abbe tu edit Marta bc😑😒

**Comment by dipesh9500** [comment]
Muh me lele😆

**Comment by Rishisuperyo-Op** [comment]
Lol

**Comment by Itzdipesh** [comment]
> Lol

![Screenshot_20210705_080217](https://user-images.githubusercontent.com/83916289/124469675-4669ec80-ddb8-11eb-8a65-05da7854c787.png)

YO STEAL😂😂😂😂😆😆😆

**Comment by Rishisuperyo-Op** [comment]
Expected 😑

**Comment by Rishisuperyo-Op** [comment]
Wait what? How? No repo here like this!

**Comment by Rishisuperyo-Op** [comment]
No fork there bro of me🙃

**Comment by Itzdipesh** [comment]
I have added my bio so it is not fork or steal🙃
